# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a84d574181939eb277038d0e1ef293c34cffe14801313762e663e96d29e9bb26e22303018deb5ea8c0f8bb1bc0a6b11cc0448180a53d797ab52af0c5781c0132

test:
  secret_key_base: 5f80e18550dca4c333da14bbaac4cbb7ca29ddac503fcf6202eaa9a7c59e44771fca511d59c3bc0bb4b2b1178d63051f7910e604d09d47d164a267c8fafccb48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
